### ISSUE TITLE
Fix "Cross Site Forgery" issue on Test

### ISSUE THREAD

**Issue by margaret-bywater** [bywatersolutions/rtenhancements#23]
An error that sporadically happens and can cause weird problems. 

> Possible cross-site request forgery
> RT has detected a possible cross-site request forgery for this request, because the Referrer header supplied by your browser (rt.bwsdocker1.bywatersolutions.com:80) is not allowed by RT's configured hostname (rt.bwsdocker1.bywatersolutions.com:8080). A malicious attacker may be trying to modify RT's configuration on your behalf. If you did not initiate this request, then you should alert your security team.
>If you really intended to visit http://rt.bwsdocker1.bywatersolutions.com:8080.... and modify RT's configuration, then click here to resume your request.

**Comment by bartonski** [comment]
This was fixed by updating onw of the URLs in stieconfig.

**Comment by bartonski** [comment]
Margaret got this on `Admin/Users/index.html`

**Comment by bartonski** [comment]
The problem is that (at least some) links are formatted as ``http://rt......com/Admin/CustomFields/Modify.html?Create=1`` -- without any port specified -- rather than as ``http://rt......com:8080/Admin/CustomFields/Modify.html?Create=1`` -- which specifies port 8080.

This is despite the fact that `/opt/rt4/etc/RT_SiteConfig.pm` has `$WebPort` set:

    Set($WebPort, 8080);

**Comment by margaret-bywater** [comment]
This is hardly ever happening now, so I'll retire this issue.
